[package]
name = "rust_playground"
version = "0.1.0"
authors = ["Evtimiy Mihaylov <evo@vaupe.com>"]

[dependencies]
rocket = "0.3.10"
rocket_codegen = "0.3.10"
rocket_contrib = { version = "0.3.10", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"